routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
	'uses' => 'FrontController@index',
	'as' => 'index',
]);

Route::get('/nosotros', [
	'uses' => 'FrontController@nosotros',
	'as' => 'nosotros',
]);

Route::get('/cursos', [
	'uses' => 'FrontController@cursos',
	'as' => 'cursos',
]);

Route::get('/cursos/{slug}', [
	'uses' => 'FrontController@cursosDetalle',
	'as' => 'curso.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog', [
	'uses' => 'FrontController@blog',
	'as' => 'blog',
]);

Route::get('/blog/{slug}', [
	'uses' => 'FrontController@blogDetalle',
	'as' => 'blog.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog/archivo/{autor}', [
	'uses' => 'FrontController@autorBlogList',
	'as' => 'autor.blog.list',
])->where('slug', '[\w\d\-\_]+');


Route::get('/mensaje_del_director', [
	'uses' => 'FrontController@mensaje_director',
	'as' => 'mensaje_director',
]);

Route::get('/contacto', [
	'uses' => 'FrontController@contacto',
	'as' => 'contacto',
]);

Route::get('/eventos', [
	'uses' => 'FrontController@eventos',
	'as' => 'eventos',
]);

Route::get('/galerias', [
	'uses' => 'FrontController@galerias',
	'as' => 'galerias',
]);

Route::get('/galerias/{slug}', [
	'uses' => 'FrontController@galeriaDetalle',
	'as' => 'galeria.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/info/{slug}', [
	'uses' => 'FrontController@landingDetalle',
	'as' => 'landing.detalle',
])->where('slug', '[\w\d\-\_]+');

Route::get('/info/{slug}/gracias', [
	'uses' => 'FrontController@landingSuccessDetalle',
	'as' => 'landing.success',
])->where('slug', '[\w\d\-\_]+');


Route::get('/testimonios', [
	'uses' => 'FrontController@testimonios',
	'as' => 'testimonios',
]);

Route::get('/aviso_de_privacidad', [
	'uses' => 'FrontController@privacidad',
	'as' => 'privacidad',
]);

Route::get('/terminos_y_condiciones', [
	'uses' => 'FrontController@terminos',
	'as' => 'terminos',
]);

Route::get('/busqueda-general', [
    'uses' => 'FrontSearchController@query',
    'as' => 'search.query',
]);

Route::get('/info/{slug}/guardar_contacto', [
    'uses' => 'FrontController@storeContact',
    'as' => 'contact.store.landing',
]);

Route::get('/contact_form/guardar_contacto', [
    'uses' => 'FrontController@storeContactForm',
    'as' => 'contact.store.form',
]);
 
Route::get('/gracias', [
	'uses' => 'FrontController@formSuccess',
	'as' => 'form.success',
]);

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::resource('/admin/usuarios', 'UserController');

	Route::get('/admin', [
		'uses' => 'BackController@index',
		'as' => 'home',
	]);

	Route::get('/admin/usuarios', [
		'uses' => 'AuthController@adminList',
		'as' => 'admin.index',
	]);

	Route::get('/admin/register-admin', [
		'uses' => 'AuthController@register',
		'as' => 'admin.register',
	]);

	Route::post('/admin/register-admin', [
		'uses' => 'AuthController@postRegister',
		'as' => 'admin.register',
	]);

	Route::delete('/admin/delete-admin/{id}', [
		'uses' => 'AuthController@destroy',
		'as' => 'admin.destroy',
	]);

	Route::get('/admin/perfil', [
		'uses' => 'BackController@userProfile',
		'as' => 'admin.perfil',
	]);

	Route::put('/admin/perfil/imagen/{id}', [
		'uses' => 'BackController@updateImage',
		'as' => 'admin.image.update',
	]);

	Route::put('/admin/perfil/{id}', [
		'uses' => 'BackController@updateProfile',
		'as' => 'admin.update',
	]);

	Route::resource('/admin/roles', 'RoleController');

	/*
	Route::post('/admin/registro-admin', [
		'uses' => 'UserController@postRegistro',
		'as' => 'admin.registro',
	]);
	*/

	/* -------------------------------------- */
	/* ------ BLOG, GALERIAS Y CURSOS ------- */
	/* --------------------------------.----- */

	Route::resource('/admin/blog', 'BlogController');
	Route::resource('/admin/categorias', 'CategoryController');
	Route::resource('/admin/etiquetas', 'TagController');
	Route::resource('/admin/cursos', 'CourseController');
	Route::resource('/admin/galerias', 'GalleryController');

	Route::delete('/admin/galerias/extra-destroy/{id}', [
		'uses' => 'GalleryController@softDestroy',
		'as' => 'extra.destroy',
	]);

	Route::get('/admin/galerias/dar-baja/{id}', [
		'uses' => 'GalleryController@darDeBaja',
		'as' => 'galerias.baja',
	]);

	Route::get('/admin/galerias/dar-alta/{id}', [
		'uses' => 'GalleryController@darDeAlta',
		'as' => 'galerias.alta',
	]);

	Route::post('/admin/galerias/nueva-imagen', [
		'uses' => 'GalleryController@storeImage',
		'as' => 'imagen.store',
	]);

	Route::post('/admin/galerias/nueva-imagen/{id}', [
		'uses' => 'GalleryController@editImage',
		'as' => 'imagen.edit',
	]);

	Route::resource('/admin/eventos', 'EventController');

	Route::get('/admin/eventos/destroy/{id}', [
		'uses' => 'EventController@softDestroy',
		'as' => 'eventos.hard.destroy',
	]);

	Route::resource('/admin/campanas', 'CampaignController');
	Route::resource('/admin/landing_pages', 'LandingPageController');
	Route::resource('/admin/contactos', 'ContactController');


	Route::get('/contactos_landing_exportacion/{landing}', [
		'uses' => '\App\Http\Controllers\CampaignController@export',
		'as' => 'contactos.export',
	]);

	Route::get('/contactos_exportacion', [
		'uses' => '\App\Http\Controllers\CampaignController@fullExport',
		'as' => 'contactos.full.export',
	]);

	//Route::resource('/admin/ventas/listados', 'CRMController');
	Route::resource('/admin/ventas/listados', 'SalesController');

	Route::get('/ventas_exportacion', [
		'uses' => 'SalesController@export',
		'as' => 'ventas.export',
	]);

	Route::post('/ventas_importacion', [
		'uses' => 'SalesController@import',
		'as' => 'ventas.import',
	]);

	/* VISTAS DE FILTRO CRM */

	Route::get('/admin/ventas/filtros/nuevos-registros', [
		'uses' => 'SalesController@filterNewRegistry',
		'as' => 'crm.filter_1'
	]);

	Route::get('/admin/ventas/filtros/prospectos', [
		'uses' => 'SalesController@filterProspects',
		'as' => 'crm.filter_2'
	]);

	Route::get('/admin/ventas/filtros/interesados', [
		'uses' => 'SalesController@filterInterested',
		'as' => 'crm.filter_3'
	]);

	Route::get('/admin/ventas/filtros/promesa-de-venta', [
		'uses' => 'SalesController@filterSalesPromise',
		'as' => 'crm.filter_4'
	]);

	Route::get('/admin/ventas/filtros/cierres-exitosos', [
		'uses' => 'SalesController@filterSalesComplete',
		'as' => 'crm.filter_5'
	]);

	Route::get('/admin/ventas/filtros/prospectos-detenidos', [
		'uses' => 'SalesController@filterActionRequired',
		'as' => 'crm.filter_6'
	]);

	Route::put('/admin/ventas/update-estado/{id}', [
		'uses' => 'SalesController@updateEstado',
		'as' => 'crm.updateEstado'
	]);
	
	Route::put('/admin/contactos/update-estado/{id}', [
		'uses' => 'SalesController@updateStatus',
		'as' => 'crm.updateStatus'
	]);

	/* Actualizaciones de Estado para Prospectos */

	Route::put('/admin/contactos/update-estado-global/{id}', [
		'uses' => 'SalesController@updateGlobalStatus',
		'as' => 'crm.updateGlobalStatus'
	]);

	Route::get('/admin/completar-registro/{id}', [
		'uses' => 'SalesController@completarRegistro',
		'as' => 'crm.completarRegistro'
	]);

	Route::get('/admin/completar-prospecto/{id}', [
		'uses' => 'SalesController@completarProspecto',
		'as' => 'crm.completarProspecto'
	]);

	Route::get('/admin/completar-interesado/{id}', [
		'uses' => 'SalesController@completarInteresado',
		'as' => 'crm.completarInteresado'
	]);

	Route::get('/admin/completar-promesa-de-venta/{id}', [
		'uses' => 'SalesController@completarPromesaDeVenta',
		'as' => 'crm.completarPromesaDeVenta'
	]);

	Route::get('/admin/prospecto-perdido/{id}', [
		'uses' => 'SalesController@prospectoPerdido',
		'as' => 'crm.prospectoPerdido'
	]);

	/* KPIS de Venta */

	Route::get('/admin/indicadores-ventas', [
		'uses' => 'SalesKpiController@indexKPI',
		'as' => 'ventas.kpi.index',
	]);

	Route::get('/admin/indicadores-ventas/{id}', [
		'uses' => 'SalesKpiController@showKPI',
		'as' => 'ventas.kpi.show',
	]);

	/* ------------------------- */
	/* ------------------------- */
	/* ------------------------- */
	
	Route::resource('/admin/actividades', 'ActivityController');

	Route::post('/admin/actividades/completar/{id}', [
		'uses' => 'ActivityController@completeActivity',
		'as' => 'actividades.completar'
	]);

	Route::get('/admin/actividades/prioridad/{id}', [
		'uses' => 'ActivityController@priorityActivity',
		'as' => 'actividades.prioridad'
	]);

	Route::post('/admin/actividades/{activity_id}/guardar_intento', [
		'uses' => 'ActivityController@storeTry',
		'as' => 'actividad.intento'
	]);

	Route::get('/admin/actividades/{activity_id}/guardar_intento/detalle', [
		'uses' => 'ActivityController@showTry',
		'as' => 'actividad.intento.mostrar'
	]);

	Route::resource('/admin/programas', 'ProgramController');
	Route::resource('/admin/metas-objetivos', 'GoalsController');
	Route::resource('/admin/pagos', 'PaymentController');

	/* ----------------------------- */
	/* ------ SEARCH QUERIES ------- */
	/* ----------------------------- */

	Route::get('/admin/busqueda/resultados', [
		'uses' => 'SearchController@contactsSearch',
		'as' => 'crm.search',
	]);

	/* ----------------------------- */
	/* ------ RELOJ CHECADOR ------- */
	/* ----------------------------- */

	Route::resource('/admin/reloj-checador', 'TimeClockController');

	Route::get('/admin/reloj-checador-historico', [
		'uses' => 'TimeClockController@history',
		'as' => 'reloj-checador.history'
	]);

});

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use DB;
use Auth;
use Session;

/*Modelos Disponibles */
use App\Contact;

class SearchController extends Controller
{
    public function contactsSearch(Request $request)
    {	
    	$search_query = $request->input('search_query');
    	$search_order = $request->input('search_order');
    	$search_date = $request->input('search_date');

    	if ($search_query == NULL) {

    		if ($search_order == NULL || $search_order == 0) {

    			if ($search_date) {
	    			$resultados = Contact::where('is_active', '=', true)
                    ->where(DB::raw('created_at'), 'LIKE', "%{$search_date}%")->get();

		    		return view('back.crm.search.query')->with('contacts', $resultados);
	    		}

    		}else{
    			/* Opciones de Filtro */
    			if ($search_order == 1) {
    				$resultados = Contact::where('is_active', '=', true)
                    ->orderBy('created_at', 'asc')->get();

    			}elseif ($search_order == 2) {
    				$resultados = Contact::where('is_active', '=', true)
                    ->orderBy('created_at', 'desc')->get();
    			}

    			return view('back.crm.search.query')->with('contacts', $resultados);
    		}

    	}else{
            $resultados = Contact::where('is_active', '=', true)
            ->whereHas('origin', function ($query) use ($search_query) {
                $query->where('title', 'LIKE', '%' . strtolower($search_query) . '%');
            })->orWhere('company', 'LIKE', '%' . strtolower($search_query) . '%')
            ->orWhere('name', 'LIKE', '%' . strtolower($search_query) . '%')
            ->orWhere('sur_name', 'LIKE', '%' . strtolower($search_query) . '%')
            ->orWhere('email', 'LIKE', '%' . strtolower($search_query) . '%')
            ->get();

    		return view('back.crm.search.query')->with('contacts', $resultados);

    	}
          
        if ($search_query == NULL && $search_order == NULL && search_date == NULL) {
        	$resultados = NULL;

        	return view('back.crm.search.query')->with('contacts', $resultados);
        }
    }
}

resources/views/back/crm/search/query.blade.php
@extends('back.layouts.app')

@section('stylesheets')
<link rel="stylesheet" type="text/css" href="{{ asset('css/filter_db/filter.css') }}">

<!-- Footable CSS -->
<link href="{{ asset('back/assets/plugins/footable/css/footable.core.css') }}" rel="stylesheet">
<link href="{{ asset('back/assets/css/filter-table.css') }}" rel="stylesheet">
<link href="{{ asset('back/assets/plugins/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />

<style type="text/css">
    .select2-container{
        display: block;
        width: 100% !important;
    }

    .table td, .table th {
        padding: 1.3rem .75rem;
        vertical-align: middle !important;
        font-weight: 300 !important;
    }

    sup{
    	top: -3px;
    	margin-right: 10px;
    }

    .stats .card-title{
    	margin-bottom: 0px;
    }

    .stats a{
    	font-size: .8em;
    }

    .round{
    	width: 35px !important;
    	height: 35px !important;
    }

    .round i{
    	position: relative !important;
    	line-height: 35px !important;
    	top: -5px;
    }
</style>

@endsection

@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Gestión de Relaciones con Clientes</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Inicio</a></li>
            <li class="breadcrumb-item"><a href="{{ route('listados.index') }}">CRM</a></li>
            <li class="breadcrumb-item active">Resultado de Búsqueda</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col">
        @include('back.layouts.partials._mensajes')
    </div>
</div>

<div class="section-title pt-3 pb-3">
    <div class="row align-items-center">
        <div class="col">
            <h6 class="section text-uppercase">Busqueda</h6>
            @if(Request::input('search_query') == NULL)

            @else
                <h2 class="description mb-2">Elementos que contienen: "{{ Request::input('search_query') }}"</h2>
                <h5>Se han encontrado un total de <strong>{{ $contacts->count() }}</strong> resultado(s).</h5>
            @endif
        </div>
    </div>
    <hr>
</div>

<div class="row mb-4 mt-3">
    <div class="col">
        <a href="{{ route('listados.index') }}" class="btn btn-secondary">Regresar al listado General</a>
    </div>  
</div>

<div class="row">
    <div class="col-md-12">
    	<div class="row">
		    <div class="col-md-12">
	    		<div class="card">
		            <div class="card-body">
		                <h3>Listado de Búsqueda</h3>
		                <hr>

						<table id="table-pagination" class="table m-b-0 toggle-arrow-tiny" data-page-size="10">
							<thead>
								<tr>
									<th>Fecha</th>
									<th>Prospecto</th>
									<th>Interés</th>
									<th>Asesor</th>
									<th>Campaña</th>
									<th>Estado</th>
								</tr>
							</thead>
							<tbody>
                                @foreach($contacts as $ct)
                                    <tr>
                                        <td><span class="text-muted"><i class="fa fa-clock-o"></i> {{ $ct->created_at->diffForHumans() }}</span></td>
                                        <td>
                                            <a href="{{ route('listados.show', $ct->id) }}" data-toggle="tooltip" data-placement="top" title="Ver Perfil">{{ $ct->name . ' ' . $ct->sur_name }}</a>

                                            <p style="font-size: 80%; margin-bottom: 0px; margin-top: 10px;"><i class="mdi mdi-cellphone-android"></i> {{ $ct->phone_cel }}</p>
                                            <p style="font-size: 80%; margin-bottom: 0px;"><i class="mdi mdi-email"></i> {{ $ct->email }}</p>
                                        </td>
                                        <td>
                                            @foreach($ct->interests as $int)
                                                <a class="badge-pill badge-info" href="{{ route('programas.show', $int->id) }}" data-toggle="tooltip" data-placement="top" title="Filtrar por este Interés">{{ $int->name }}</a>
                                            @endforeach
                                        </td>
                                        <td><a href="" data-toggle="tooltip" data-placement="top" title="Filtrar por Asesor">{{ $ct->sales_agent->name }}</a></td>

                                        <td>
                                            @if($ct->landing_origin_id == NULL)
                                            <span class="text-uppercase" style="font-size: .8em">Registro Manual</span>
                                            @else
                                            {{ $ct->origin->title }} <a href="" data-toggle="tooltip" data-placement="top" title="Ir a la Campaña"><i class="mdi mdi-web"></i></a>
                                            @endif
                                        </td>
                                        <td>
                                            @if($ct->status == 'Registro')
                                                <span class="badge badge-danger">{{ $ct->status }}</span>
                                            @endif

                                            @if($ct->status == 'Prospecto')
                                                <span class="badge badge-danger">{{ $ct->status }}</span>
                                            @endif

                                            @if($ct->status == 'Interesado')
                                                <span class="badge badge-warning">{{ $ct->status }}</span>
                                            @endif

                                            @if($ct->status == 'Promesa de Venta')
                                                <span class="badge badge-info">{{ $ct->status }}</span>
                                            @endif
                                            
                                            @if($ct->status == 'Cierre Exitoso')
                                                <span class="badge badge-success">{{ $ct->status }}</span>
                                            @endif

                                            @if($ct->status == 'Cierre Perdido')
                                                <span class="badge badge-danger">{{ $ct->status }}</span>
                                            @endif
                                            
                                        </td>
                                    </tr>
                                @endforeach
							</tbody>
							<tfoot>
								<tr>
									<td colspan="12">
										<div class="text-right">
											<ul class="pagination pagination-split m-t-30"> </ul>
										</div>
									</td>
								</tr>
							</tfoot>
						</table>
		            </div>
		        </div>
	    	</div>
    	</div>
    </div>
</div>

<style type="text/css">
    .pagination{
        justify-content: center;
        margin-top: 10px;
    }
</style>

<script type="text/javascript">
     (function() {
       if (document.querySelector('.pagination')!==null) {

         // Set paginator ul and li
         var paginator_ul = document.getElementsByClassName('pagination')[0],
             paginator_li = paginator_ul.getElementsByTagName("LI");

         [].forEach.call(paginator_li, function(li) {
             li.className += " page-item";
             li.firstChild.className += " page-link";
         });
       }
    })();
</script>
@endsection

@section('scripts')
<script src="{{ asset('back/assets/plugins/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>

<script type="text/javascript">
    $(".select2").select2();
</script>
<!-- Footable -->
<script src="{{ asset('back/assets/plugins/footable/js/footable.all.min.js') }}"></script>

<script src="{{ asset('js/filter_db/filter.js') }}"></script>

<script type="text/javascript">
	$(function () {
	  $('[data-toggle="tooltip"]').tooltip()
	})
</script>
@endsection