routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
	'uses' => 'FrontController@index',
	'as' => 'index',
]);

Route::get('/nosotros', [
	'uses' => 'FrontController@nosotros',
	'as' => 'nosotros',
]);

Route::get('/cursos', [
	'uses' => 'FrontController@cursos',
	'as' => 'cursos',
]);

Route::get('/cursos/{slug}', [
	'uses' => 'FrontController@cursosDetalle',
	'as' => 'curso.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog', [
	'uses' => 'FrontController@blog',
	'as' => 'blog',
]);

Route::get('/blog/{slug}', [
	'uses' => 'FrontController@blogDetalle',
	'as' => 'blog.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog/archivo/{autor}', [
	'uses' => 'FrontController@autorBlogList',
	'as' => 'autor.blog.list',
])->where('slug', '[\w\d\-\_]+');


Route::get('/mensaje_del_director', [
	'uses' => 'FrontController@mensaje_director',
	'as' => 'mensaje_director',
]);

Route::get('/contacto', [
	'uses' => 'FrontController@contacto',
	'as' => 'contacto',
]);

Route::get('/eventos', [
	'uses' => 'FrontController@eventos',
	'as' => 'eventos',
]);

Route::get('/galerias', [
	'uses' => 'FrontController@galerias',
	'as' => 'galerias',
]);

Route::get('/galerias/{slug}', [
	'uses' => 'FrontController@galeriaDetalle',
	'as' => 'galeria.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/info/{slug}', [
	'uses' => 'FrontController@landingDetalle',
	'as' => 'landing.detalle',
])->where('slug', '[\w\d\-\_]+');

Route::get('/info/{slug}/gracias', [
	'uses' => 'FrontController@landingSuccessDetalle',
	'as' => 'landing.success',
])->where('slug', '[\w\d\-\_]+');


Route::get('/testimonios', [
	'uses' => 'FrontController@testimonios',
	'as' => 'testimonios',
]);

Route::get('/aviso_de_privacidad', [
	'uses' => 'FrontController@privacidad',
	'as' => 'privacidad',
]);

Route::get('/terminos_y_condiciones', [
	'uses' => 'FrontController@terminos',
	'as' => 'terminos',
]);

Route::get('/busqueda-general', [
    'uses' => 'FrontSearchController@query',
    'as' => 'search.query',
]);

Route::get('/info/{slug}/guardar_contacto', [
    'uses' => 'FrontController@storeContact',
    'as' => 'contact.store.landing',
]);

Route::get('/contact_form/guardar_contacto', [
    'uses' => 'FrontController@storeContactForm',
    'as' => 'contact.store.form',
]);
 
Route::get('/gracias', [
	'uses' => 'FrontController@formSuccess',
	'as' => 'form.success',
]);

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::resource('/admin/usuarios', 'UserController');

	Route::get('/admin', [
		'uses' => 'BackController@index',
		'as' => 'home',
	]);

	Route::get('/admin/usuarios', [
		'uses' => 'AuthController@adminList',
		'as' => 'admin.index',
	]);

	Route::get('/admin/register-admin', [
		'uses' => 'AuthController@register',
		'as' => 'admin.register',
	]);

	Route::post('/admin/register-admin', [
		'uses' => 'AuthController@postRegister',
		'as' => 'admin.register',
	]);

	Route::delete('/admin/delete-admin/{id}', [
		'uses' => 'AuthController@destroy',
		'as' => 'admin.destroy',
	]);

	Route::get('/admin/perfil', [
		'uses' => 'BackController@userProfile',
		'as' => 'admin.perfil',
	]);

	Route::put('/admin/perfil/imagen/{id}', [
		'uses' => 'BackController@updateImage',
		'as' => 'admin.image.update',
	]);

	Route::put('/admin/perfil/{id}', [
		'uses' => 'BackController@updateProfile',
		'as' => 'admin.update',
	]);

	Route::resource('/admin/roles', 'RoleController');

	/*
	Route::post('/admin/registro-admin', [
		'uses' => 'UserController@postRegistro',
		'as' => 'admin.registro',
	]);
	*/

	/* -------------------------------------- */
	/* ------ BLOG, GALERIAS Y CURSOS ------- */
	/* --------------------------------.----- */

	Route::resource('/admin/blog', 'BlogController');
	Route::resource('/admin/categorias', 'CategoryController');
	Route::resource('/admin/etiquetas', 'TagController');
	Route::resource('/admin/cursos', 'CourseController');
	Route::resource('/admin/galerias', 'GalleryController');

	Route::delete('/admin/galerias/extra-destroy/{id}', [
		'uses' => 'GalleryController@softDestroy',
		'as' => 'extra.destroy',
	]);

	Route::get('/admin/galerias/dar-baja/{id}', [
		'uses' => 'GalleryController@darDeBaja',
		'as' => 'galerias.baja',
	]);

	Route::get('/admin/galerias/dar-alta/{id}', [
		'uses' => 'GalleryController@darDeAlta',
		'as' => 'galerias.alta',
	]);

	Route::post('/admin/galerias/nueva-imagen', [
		'uses' => 'GalleryController@storeImage',
		'as' => 'imagen.store',
	]);

	Route::post('/admin/galerias/nueva-imagen/{id}', [
		'uses' => 'GalleryController@editImage',
		'as' => 'imagen.edit',
	]);

	Route::resource('/admin/eventos', 'EventController');

	Route::get('/admin/eventos/destroy/{id}', [
		'uses' => 'EventController@softDestroy',
		'as' => 'eventos.hard.destroy',
	]);

	Route::resource('/admin/campanas', 'CampaignController');
	Route::resource('/admin/landing_pages', 'LandingPageController');
	Route::resource('/admin/contactos', 'ContactController');


	Route::get('/contactos_landing_exportacion/{landing}', [
		'uses' => '\App\Http\Controllers\CampaignController@export',
		'as' => 'contactos.export',
	]);

	Route::get('/contactos_exportacion', [
		'uses' => '\App\Http\Controllers\CampaignController@fullExport',
		'as' => 'contactos.full.export',
	]);

	//Route::resource('/admin/ventas/listados', 'CRMController');
	Route::resource('/admin/ventas/listados', 'SalesController');

	Route::get('/ventas_exportacion', [
		'uses' => 'SalesController@export',
		'as' => 'ventas.export',
	]);

	Route::post('/ventas_importacion', [
		'uses' => 'SalesController@import',
		'as' => 'ventas.import',
	]);

	/* VISTAS DE FILTRO CRM */

	Route::get('/admin/ventas/filtros/nuevos-registros', [
		'uses' => 'SalesController@filterNewRegistry',
		'as' => 'crm.filter_1'
	]);

	Route::get('/admin/ventas/filtros/prospectos', [
		'uses' => 'SalesController@filterProspects',
		'as' => 'crm.filter_2'
	]);

	Route::get('/admin/ventas/filtros/interesados', [
		'uses' => 'SalesController@filterInterested',
		'as' => 'crm.filter_3'
	]);

	Route::get('/admin/ventas/filtros/promesa-de-venta', [
		'uses' => 'SalesController@filterSalesPromise',
		'as' => 'crm.filter_4'
	]);

	Route::get('/admin/ventas/filtros/cierres-exitosos', [
		'uses' => 'SalesController@filterSalesComplete',
		'as' => 'crm.filter_5'
	]);

	Route::get('/admin/ventas/filtros/prospectos-detenidos', [
		'uses' => 'SalesController@filterActionRequired',
		'as' => 'crm.filter_6'
	]);

	Route::put('/admin/ventas/update-estado/{id}', [
		'uses' => 'SalesController@updateEstado',
		'as' => 'crm.updateEstado'
	]);
	
	Route::put('/admin/contactos/update-estado/{id}', [
		'uses' => 'SalesController@updateStatus',
		'as' => 'crm.updateStatus'
	]);

	/* Actualizaciones de Estado para Prospectos */

	Route::put('/admin/contactos/update-estado-global/{id}', [
		'uses' => 'SalesController@updateGlobalStatus',
		'as' => 'crm.updateGlobalStatus'
	]);

	Route::get('/admin/completar-registro/{id}', [
		'uses' => 'SalesController@completarRegistro',
		'as' => 'crm.completarRegistro'
	]);

	Route::get('/admin/completar-prospecto/{id}', [
		'uses' => 'SalesController@completarProspecto',
		'as' => 'crm.completarProspecto'
	]);

	Route::get('/admin/completar-interesado/{id}', [
		'uses' => 'SalesController@completarInteresado',
		'as' => 'crm.completarInteresado'
	]);

	Route::get('/admin/completar-promesa-de-venta/{id}', [
		'uses' => 'SalesController@completarPromesaDeVenta',
		'as' => 'crm.completarPromesaDeVenta'
	]);

	Route::get('/admin/prospecto-perdido/{id}', [
		'uses' => 'SalesController@prospectoPerdido',
		'as' => 'crm.prospectoPerdido'
	]);

	/* KPIS de Venta */

	Route::get('/admin/indicadores-ventas', [
		'uses' => 'SalesKpiController@indexKPI',
		'as' => 'ventas.kpi.index',
	]);

	Route::get('/admin/indicadores-ventas/{id}', [
		'uses' => 'SalesKpiController@showKPI',
		'as' => 'ventas.kpi.show',
	]);

	/* ------------------------- */
	/* ------------------------- */
	/* ------------------------- */
	
	Route::resource('/admin/actividades', 'ActivityController');

	Route::post('/admin/actividades/completar/{id}', [
		'uses' => 'ActivityController@completeActivity',
		'as' => 'actividades.completar'
	]);

	Route::get('/admin/actividades/prioridad/{id}', [
		'uses' => 'ActivityController@priorityActivity',
		'as' => 'actividades.prioridad'
	]);

	Route::post('/admin/actividades/{activity_id}/guardar_intento', [
		'uses' => 'ActivityController@storeTry',
		'as' => 'actividad.intento'
	]);

	Route::get('/admin/actividades/{activity_id}/guardar_intento/detalle', [
		'uses' => 'ActivityController@showTry',
		'as' => 'actividad.intento.mostrar'
	]);

	Route::resource('/admin/programas', 'ProgramController');
	Route::resource('/admin/metas-objetivos', 'GoalsController');
	Route::resource('/admin/pagos', 'PaymentController');

	/* ----------------------------- */
	/* ------ SEARCH QUERIES ------- */
	/* ----------------------------- */

	Route::get('/admin/busqueda/resultados', [
		'uses' => 'SearchController@contactsSearch',
		'as' => 'crm.search',
	]);

	/* ----------------------------- */
	/* ------ RELOJ CHECADOR ------- */
	/* ----------------------------- */

	Route::resource('/admin/reloj-checador', 'TimeClockController');

	Route::get('/admin/reloj-checador-historico', [
		'uses' => 'TimeClockController@history',
		'as' => 'reloj-checador.history'
	]);

});

app/Http/Controllers/BackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use Image;
use Session;

use Carbon\Carbon;
use App\Contact;
use App\Goals;
use App\Activity;
use App\Blog;
use App\User;

class BackController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $activities = Activity::where('issuer_id', Auth::user()->id)->where('completed', false)->where('activity_status', '!=', 'Incompleto por Cierre')->get();

        $activities_completed = Activity::where('issuer_id', Auth::user()->id)->where('completed', true)->count();

        $prospect_count = Contact::where('status', 'Prospecto')->where('assigned_to', Auth::user()->id)->count();
        
        $today = Carbon::now();
        $last_days = Carbon::now()->subDays(3);

        $alert_prospect = Contact::where('updated_at', '<=', $last_days)->where('status', '!=', 'Cierre Exitoso')->count();

        $blog = Blog::all()->count();

        /* KPI's Ventas */
        $venta_anual = Goals::where('name', 'Venta Total Anual')->firstOrFail();
        $cierres_mensuales = Goals::where('name', 'Cierres Mensuales')->firstOrFail();
        $promesa_venta = Goals::where('name', 'Promesa de Venta')->firstOrFail();

        $year_start = Carbon::now()->startOfYear();
        $year_end = Carbon::now()->endOfYear();

        $month_start = Carbon::now()->startOfMonth();
        $month_end = Carbon::now()->endOfMonth();

        $week_start = Carbon::now()->startOfWeek();
        $week_end = Carbon::now()->endOfWeek();

        $today = Carbon::now()->format('Y-m-d');

        $ventas_total = Contact::where('closing_date', '<=', $year_end)
        ->where('closing_date', '>=', $year_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_mes = Contact::where('closing_date', '<=', $month_end)
        ->where('closing_date', '>=', $month_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_semana = Contact::where('closing_date', '<=', $week_end)
        ->where('closing_date', '>=', $week_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_hoy = Contact::where('closing_date', '<=', $today)
        ->where('closing_date', '>=', $today)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ven_total = 0;
        $ven_mes = 0;
        $ven_semana = 0;

        foreach ($ventas_total as $v_total) {
            foreach($v_total->interests as $v)
            {
               $ven_total += $v->normal_price;
            };
        };

        foreach ($ventas_mes as $v_month) {
            foreach($v_month->interests as $v)
            {
               $ven_mes += $v->normal_price;
            };
        };

        foreach ($ventas_semana as $v_week) {
            foreach($v_week->interests as $v)
            {
               $ven_semana += $v->normal_price;
            };
        };

        $ven_total;
        $ven_mes;
        $ven_semana;

        return view('back.index')
        ->with('activities', $activities)
        ->with('activities_completed', $activities_completed)
        ->with('prospect_count', $prospect_count)
        ->with('alert_prospect', $alert_prospect)
        ->with('blog', $blog)
        ->with('ven_total', $ven_total)
        ->with('ven_mes', $ven_mes)
        ->with('ven_semana', $ven_semana)
        ->with('ventas_semana', $ventas_semana)
        ->with('ventas_mes', $ventas_mes)
        ->with('ventas_hoy', $ventas_hoy)
        ->with('venta_anual', $venta_anual)
        ->with('cierres_mensuales', $cierres_mensuales);
    }

    public function userProfile()
    {
        return view('back.users.profile');
    }

    public function updateProfile(Request $request, $id)
    {
        // Guardar datos a la BD, usar el modelo con funcion find() para encontrar el elemento que estamos editabdo por medio del ID
        $user = User::find($id);

        if($request->password == NULL){
            $user->name = $request->input('name');
            $user->email = $request->input('email');
        }else{
            $user->password = bcrypt($request->input('password'));
        }
        
        $user->save();

        // Mensaje de aviso server-side
        Session::flash('success', 'Tu cuenta se actualizó exitosamente.');
        return redirect()->route('admin.perfil');
    }

    public function updateImage(Request $request, $id)
    {
        $user = User::find($id);
        
        $user->image = $request->user_imagen;

        if ($request->hasFile('user_image')) {
            $user_image = $request->file('user_image');
            $filename = 'user_img' . time() . '.' . $user_image->getClientOriginalExtension();
            $location = public_path('img/usuarios/' . $filename);

            Image::make($user_image)->resize(400,null, function($constraint){ $constraint->aspectRatio(); })->save($location);

            $user->image = $filename;
        }

        $user->save();

        Session::flash('success', 'La imagen de tu perfil ha sido editada exitosamente.');
        return redirect()->route('admin.perfil');
    }
}

resources/views/back/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>UBR | Panel Administrativo</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('back/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('back/assets/plugins/perfect-scrollbar/css/perfect-scrollbar.css') }}" rel="stylesheet">

    @yield('stylesheets')

    <!-- Custom CSS -->
    <link href="{{ asset('back/css/style.css') }}" rel="stylesheet">
    <!-- Dashboard 1 Page CSS -->
    <link href="{{ asset('back/css/pages/dashboard4.css') }}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{{ asset('back/css/colors/default.css') }}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">

	<div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Cargando contenido...</p>
        </div>
    </div>

	<div id="main-wrapper">
		@include('back.layouts.nav')
		@include('back.layouts.sidebar')
				
		<div class="page-wrapper">
			<div class="container-fluid">
				@yield('content')
			</div>

			@include('back.layouts.footer')
		</div>
	</div>

		
	<!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ asset('back/assets/plugins/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap popper Core JavaScript -->
    <script src="{{ asset('back/assets/plugins/bootstrap/js/popper.min.js') }}"></script>
    <script src="{{ asset('back/assets/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ asset('back/js/perfect-scrollbar.jquery.min.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('back/js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('back/js/sidebarmenu.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('back/js/custom.min.js') }}"></script>

    @include('back.layouts.partials._timeclock')

    <script type="text/javascript">
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        });
    </script>
    @yield('scripts')
</body>
</html>

resources/views/back/layouts/footer.blade.php
<footer class="footer"> © 2019 Universidad de Bienes Raíces - Todos los derechos Reservados</footer>

resources/views/back/layouts/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-devider"></li>
                <li class="nav-small-cap">PERSONAL</li>
                <li><a class="has-arrow waves-effect waves-dark" href="{{ route('home') }}" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Vista Rápida</span></a></li>

                @if(auth()->user()->can('all_access') || auth()->user()->can('sales_access')) 
                <li><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-sale"></i><span class="hide-menu">Ventas</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('listados.index') }}"><i class="mdi mdi-view-dashboard"></i> Vista General</a></li>
                        <li><a href="{{ route('ventas.kpi.index') }}"><i class="mdi mdi-trending-up"></i> KPI's</a></li>
                    </ul>
                </li>
                @endif

                {{--
                @if(auth()->user()->can('all_access') || auth()->user()->can('payment_access')) 
                <li class="two-column"><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-wallet"></i><span class="hide-menu">Pagos</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="app-chat.html"><i class="mdi mdi-view-dashboard"></i> Vista General</a></li>
                        <li><a href="app-chat.html"><i class="mdi mdi-credit-card"></i> Pagos Manuales</a></li>
                        <li><a href="app-chat.html"><i class="mdi mdi-trending-up"></i> KPI's</a></li>
                        
                    </ul>
                </li>
                @endif
                --}}

                <!--
                <li><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-book-open-variant"></i><span class="hide-menu">Noticias / Blog</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <a class="has-arrow" href="#" aria-expanded="false">Publicaciones</a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="{{ route('blog.create') }}">Crear Nueva</a></li>
                                <li><a href="{{ route('blog.index') }}">Ver Todas</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ route('categorias.index') }}">Categorías</a></li>
                        <li><a href="{{ route('etiquetas.index') }}">Etiquetas</a></li>
                    </ul>
                </li>
                -->  

                @if(auth()->user()->can('all_access') || auth()->user()->can('admin_access_services')) 
                <li class="two-column"><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-bullhorn"></i><span class="hide-menu">Marketing </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('campanas.index') }}"><i class="mdi mdi-trophy-award"></i> Campañas</a></li>
                        <li><a href="{{ route('galerias.index') }}"><i class="mdi mdi-image-filter"></i> Galerías</a></li>
                        <li><a href="{{ route('cursos.index') }}"><i class="mdi mdi-theater"></i> Cursos</a></li>
                        <li><a href="{{ route('programas.index') }}"><i class="mdi mdi-timetable"></i> Servicios / Programas</a></li>

                        <li><a href="#" class="has-arrow"><i class="mdi mdi-pencil"></i> Blog / Noticias</a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="{{ route('blog.index') }}">Listado General</a></li>
                                <li><a href="{{ route('categorias.index') }}">Categorías</a></li>
                                <li><a href="{{ route('etiquetas.index') }}">Etiquetas</a></li>
                            </ul>
                        </li>

                        <li><a href="{{ route('eventos.index') }}"><i class="mdi mdi-timetable"></i> Eventos</a></li>
                        <!--<li><a href="javascript:void(0)"><i class="mdi mdi-flask-outline"></i> Becas</a></li>-->
                    </ul>
                </li>
                @endif

                @if(auth()->user()->can('all_access') || auth()->user()->can('admin_access')) 
                <li><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-television-guide"></i><span class="hide-menu">Administrativo</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('reloj-checador.index') }}"><i class="mdi mdi-view-dashboard"></i> 
                            Entradas de Hoy</a>
                        </li>
                        <li><a href="{{ route('reloj-checador.history') }}"><i class="mdi mdi-view-dashboard"></i> Historial Reloj Checador</a></li>
                    </ul>
                </li>
                @endif

                @if(auth()->user()->can('all_access') || auth()->user()->can('admin_access')) 
                <li><a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-account-multiple"></i><span class="hide-menu">Usuarios / Roles</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.index') }}"><i class="mdi mdi-view-dashboard"></i> Listado General</a></li>
                        <li><a href="{{ route('roles.index') }}"><i class="mdi mdi-account-settings"></i> Roles</a></li>

                        <li><a href="{{ route('register') }}"><i class="mdi mdi-account-plus"></i> Registrar Nuevo Usuario</a></li>
                    </ul>
                </li>
                @endif
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>