routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
	'uses' => 'FrontController@index',
	'as' => 'index',
]);

Route::get('/nosotros', [
	'uses' => 'FrontController@nosotros',
	'as' => 'nosotros',
]);

Route::get('/cursos', [
	'uses' => 'FrontController@cursos',
	'as' => 'cursos',
]);

Route::get('/cursos/{slug}', [
	'uses' => 'FrontController@cursosDetalle',
	'as' => 'curso.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog', [
	'uses' => 'FrontController@blog',
	'as' => 'blog',
]);

Route::get('/blog/{slug}', [
	'uses' => 'FrontController@blogDetalle',
	'as' => 'blog.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/blog/archivo/{autor}', [
	'uses' => 'FrontController@autorBlogList',
	'as' => 'autor.blog.list',
])->where('slug', '[\w\d\-\_]+');


Route::get('/mensaje_del_director', [
	'uses' => 'FrontController@mensaje_director',
	'as' => 'mensaje_director',
]);

Route::get('/contacto', [
	'uses' => 'FrontController@contacto',
	'as' => 'contacto',
]);

Route::get('/eventos', [
	'uses' => 'FrontController@eventos',
	'as' => 'eventos',
]);

Route::get('/galerias', [
	'uses' => 'FrontController@galerias',
	'as' => 'galerias',
]);

Route::get('/galerias/{slug}', [
	'uses' => 'FrontController@galeriaDetalle',
	'as' => 'galeria.detalle',
])->where('slug', '[\w\d\-\_]+');


Route::get('/info/{slug}', [
	'uses' => 'FrontController@landingDetalle',
	'as' => 'landing.detalle',
])->where('slug', '[\w\d\-\_]+');

Route::get('/info/{slug}/gracias', [
	'uses' => 'FrontController@landingSuccessDetalle',
	'as' => 'landing.success',
])->where('slug', '[\w\d\-\_]+');


Route::get('/testimonios', [
	'uses' => 'FrontController@testimonios',
	'as' => 'testimonios',
]);

Route::get('/aviso_de_privacidad', [
	'uses' => 'FrontController@privacidad',
	'as' => 'privacidad',
]);

Route::get('/terminos_y_condiciones', [
	'uses' => 'FrontController@terminos',
	'as' => 'terminos',
]);

Route::get('/busqueda-general', [
    'uses' => 'FrontSearchController@query',
    'as' => 'search.query',
]);

Route::get('/info/{slug}/guardar_contacto', [
    'uses' => 'FrontController@storeContact',
    'as' => 'contact.store.landing',
]);

Route::get('/contact_form/guardar_contacto', [
    'uses' => 'FrontController@storeContactForm',
    'as' => 'contact.store.form',
]);
 
Route::get('/gracias', [
	'uses' => 'FrontController@formSuccess',
	'as' => 'form.success',
]);

Auth::routes();

Route::group(['middleware' => 'auth'], function(){
	Route::resource('/admin/usuarios', 'UserController');

	Route::get('/admin', [
		'uses' => 'BackController@index',
		'as' => 'home',
	]);

	Route::get('/admin/usuarios', [
		'uses' => 'AuthController@adminList',
		'as' => 'admin.index',
	]);

	Route::get('/admin/register-admin', [
		'uses' => 'AuthController@register',
		'as' => 'admin.register',
	]);

	Route::post('/admin/register-admin', [
		'uses' => 'AuthController@postRegister',
		'as' => 'admin.register',
	]);

	Route::delete('/admin/delete-admin/{id}', [
		'uses' => 'AuthController@destroy',
		'as' => 'admin.destroy',
	]);

	Route::get('/admin/perfil', [
		'uses' => 'BackController@userProfile',
		'as' => 'admin.perfil',
	]);

	Route::put('/admin/perfil/imagen/{id}', [
		'uses' => 'BackController@updateImage',
		'as' => 'admin.image.update',
	]);

	Route::put('/admin/perfil/{id}', [
		'uses' => 'BackController@updateProfile',
		'as' => 'admin.update',
	]);

	Route::resource('/admin/roles', 'RoleController');

	/*
	Route::post('/admin/registro-admin', [
		'uses' => 'UserController@postRegistro',
		'as' => 'admin.registro',
	]);
	*/

	/* -------------------------------------- */
	/* ------ BLOG, GALERIAS Y CURSOS ------- */
	/* --------------------------------.----- */

	Route::resource('/admin/blog', 'BlogController');
	Route::resource('/admin/categorias', 'CategoryController');
	Route::resource('/admin/etiquetas', 'TagController');
	Route::resource('/admin/cursos', 'CourseController');
	Route::resource('/admin/galerias', 'GalleryController');

	Route::delete('/admin/galerias/extra-destroy/{id}', [
		'uses' => 'GalleryController@softDestroy',
		'as' => 'extra.destroy',
	]);

	Route::get('/admin/galerias/dar-baja/{id}', [
		'uses' => 'GalleryController@darDeBaja',
		'as' => 'galerias.baja',
	]);

	Route::get('/admin/galerias/dar-alta/{id}', [
		'uses' => 'GalleryController@darDeAlta',
		'as' => 'galerias.alta',
	]);

	Route::post('/admin/galerias/nueva-imagen', [
		'uses' => 'GalleryController@storeImage',
		'as' => 'imagen.store',
	]);

	Route::post('/admin/galerias/nueva-imagen/{id}', [
		'uses' => 'GalleryController@editImage',
		'as' => 'imagen.edit',
	]);

	Route::resource('/admin/eventos', 'EventController');

	Route::get('/admin/eventos/destroy/{id}', [
		'uses' => 'EventController@softDestroy',
		'as' => 'eventos.hard.destroy',
	]);

	Route::resource('/admin/campanas', 'CampaignController');
	Route::resource('/admin/landing_pages', 'LandingPageController');
	Route::resource('/admin/contactos', 'ContactController');


	Route::get('/contactos_landing_exportacion/{landing}', [
		'uses' => '\App\Http\Controllers\CampaignController@export',
		'as' => 'contactos.export',
	]);

	Route::get('/contactos_exportacion', [
		'uses' => '\App\Http\Controllers\CampaignController@fullExport',
		'as' => 'contactos.full.export',
	]);

	//Route::resource('/admin/ventas/listados', 'CRMController');
	Route::resource('/admin/ventas/listados', 'SalesController');

	Route::get('/ventas_exportacion', [
		'uses' => 'SalesController@export',
		'as' => 'ventas.export',
	]);

	Route::post('/ventas_importacion', [
		'uses' => 'SalesController@import',
		'as' => 'ventas.import',
	]);

	/* VISTAS DE FILTRO CRM */

	Route::get('/admin/ventas/filtros/nuevos-registros', [
		'uses' => 'SalesController@filterNewRegistry',
		'as' => 'crm.filter_1'
	]);

	Route::get('/admin/ventas/filtros/prospectos', [
		'uses' => 'SalesController@filterProspects',
		'as' => 'crm.filter_2'
	]);

	Route::get('/admin/ventas/filtros/interesados', [
		'uses' => 'SalesController@filterInterested',
		'as' => 'crm.filter_3'
	]);

	Route::get('/admin/ventas/filtros/promesa-de-venta', [
		'uses' => 'SalesController@filterSalesPromise',
		'as' => 'crm.filter_4'
	]);

	Route::get('/admin/ventas/filtros/cierres-exitosos', [
		'uses' => 'SalesController@filterSalesComplete',
		'as' => 'crm.filter_5'
	]);

	Route::get('/admin/ventas/filtros/prospectos-detenidos', [
		'uses' => 'SalesController@filterActionRequired',
		'as' => 'crm.filter_6'
	]);

	Route::put('/admin/ventas/update-estado/{id}', [
		'uses' => 'SalesController@updateEstado',
		'as' => 'crm.updateEstado'
	]);
	
	Route::put('/admin/contactos/update-estado/{id}', [
		'uses' => 'SalesController@updateStatus',
		'as' => 'crm.updateStatus'
	]);

	/* Actualizaciones de Estado para Prospectos */

	Route::put('/admin/contactos/update-estado-global/{id}', [
		'uses' => 'SalesController@updateGlobalStatus',
		'as' => 'crm.updateGlobalStatus'
	]);

	Route::get('/admin/completar-registro/{id}', [
		'uses' => 'SalesController@completarRegistro',
		'as' => 'crm.completarRegistro'
	]);

	Route::get('/admin/completar-prospecto/{id}', [
		'uses' => 'SalesController@completarProspecto',
		'as' => 'crm.completarProspecto'
	]);

	Route::get('/admin/completar-interesado/{id}', [
		'uses' => 'SalesController@completarInteresado',
		'as' => 'crm.completarInteresado'
	]);

	Route::get('/admin/completar-promesa-de-venta/{id}', [
		'uses' => 'SalesController@completarPromesaDeVenta',
		'as' => 'crm.completarPromesaDeVenta'
	]);

	Route::get('/admin/prospecto-perdido/{id}', [
		'uses' => 'SalesController@prospectoPerdido',
		'as' => 'crm.prospectoPerdido'
	]);

	/* KPIS de Venta */

	Route::get('/admin/indicadores-ventas', [
		'uses' => 'SalesKpiController@indexKPI',
		'as' => 'ventas.kpi.index',
	]);

	Route::get('/admin/indicadores-ventas/{id}', [
		'uses' => 'SalesKpiController@showKPI',
		'as' => 'ventas.kpi.show',
	]);

	/* ------------------------- */
	/* ------------------------- */
	/* ------------------------- */
	
	Route::resource('/admin/actividades', 'ActivityController');

	Route::post('/admin/actividades/completar/{id}', [
		'uses' => 'ActivityController@completeActivity',
		'as' => 'actividades.completar'
	]);

	Route::get('/admin/actividades/prioridad/{id}', [
		'uses' => 'ActivityController@priorityActivity',
		'as' => 'actividades.prioridad'
	]);

	Route::post('/admin/actividades/{activity_id}/guardar_intento', [
		'uses' => 'ActivityController@storeTry',
		'as' => 'actividad.intento'
	]);

	Route::get('/admin/actividades/{activity_id}/guardar_intento/detalle', [
		'uses' => 'ActivityController@showTry',
		'as' => 'actividad.intento.mostrar'
	]);

	Route::resource('/admin/programas', 'ProgramController');
	Route::resource('/admin/metas-objetivos', 'GoalsController');
	Route::resource('/admin/pagos', 'PaymentController');

	/* ----------------------------- */
	/* ------ SEARCH QUERIES ------- */
	/* ----------------------------- */

	Route::get('/admin/busqueda/resultados', [
		'uses' => 'SearchController@contactsSearch',
		'as' => 'crm.search',
	]);

	/* ----------------------------- */
	/* ------ RELOJ CHECADOR ------- */
	/* ----------------------------- */

	Route::resource('/admin/reloj-checador', 'TimeClockController');

	Route::get('/admin/reloj-checador-historico', [
		'uses' => 'TimeClockController@history',
		'as' => 'reloj-checador.history'
	]);

});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    public function autor()
    {
        return $this->belongsTo(\App\User::class, 'autor_id', 'id');
    }

    public function categoria()
    {
        return $this->belongsTo(\App\Category::class, 'category_id', 'id');
    }

    public function etiquetas()
    {
    	return $this->belongsToMany('App\Tag', 'tags_blogs', 'blog_id', 'tag_id');
    }
}

app/Http/Controllers/BackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use Image;
use Session;

use Carbon\Carbon;
use App\Contact;
use App\Goals;
use App\Activity;
use App\Blog;
use App\User;

class BackController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $activities = Activity::where('issuer_id', Auth::user()->id)->where('completed', false)->where('activity_status', '!=', 'Incompleto por Cierre')->get();

        $activities_completed = Activity::where('issuer_id', Auth::user()->id)->where('completed', true)->count();

        $prospect_count = Contact::where('status', 'Prospecto')->where('assigned_to', Auth::user()->id)->count();
        
        $today = Carbon::now();
        $last_days = Carbon::now()->subDays(3);

        $alert_prospect = Contact::where('updated_at', '<=', $last_days)->where('status', '!=', 'Cierre Exitoso')->count();

        $blog = Blog::all()->count();

        /* KPI's Ventas */
        $venta_anual = Goals::where('name', 'Venta Total Anual')->firstOrFail();
        $cierres_mensuales = Goals::where('name', 'Cierres Mensuales')->firstOrFail();
        $promesa_venta = Goals::where('name', 'Promesa de Venta')->firstOrFail();

        $year_start = Carbon::now()->startOfYear();
        $year_end = Carbon::now()->endOfYear();

        $month_start = Carbon::now()->startOfMonth();
        $month_end = Carbon::now()->endOfMonth();

        $week_start = Carbon::now()->startOfWeek();
        $week_end = Carbon::now()->endOfWeek();

        $today = Carbon::now()->format('Y-m-d');

        $ventas_total = Contact::where('closing_date', '<=', $year_end)
        ->where('closing_date', '>=', $year_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_mes = Contact::where('closing_date', '<=', $month_end)
        ->where('closing_date', '>=', $month_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_semana = Contact::where('closing_date', '<=', $week_end)
        ->where('closing_date', '>=', $week_start)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ventas_hoy = Contact::where('closing_date', '<=', $today)
        ->where('closing_date', '>=', $today)
        ->where('status', 'Cierre Exitoso')
        ->get();

        $ven_total = 0;
        $ven_mes = 0;
        $ven_semana = 0;

        foreach ($ventas_total as $v_total) {
            foreach($v_total->interests as $v)
            {
               $ven_total += $v->normal_price;
            };
        };

        foreach ($ventas_mes as $v_month) {
            foreach($v_month->interests as $v)
            {
               $ven_mes += $v->normal_price;
            };
        };

        foreach ($ventas_semana as $v_week) {
            foreach($v_week->interests as $v)
            {
               $ven_semana += $v->normal_price;
            };
        };

        $ven_total;
        $ven_mes;
        $ven_semana;

        return view('back.index')
        ->with('activities', $activities)
        ->with('activities_completed', $activities_completed)
        ->with('prospect_count', $prospect_count)
        ->with('alert_prospect', $alert_prospect)
        ->with('blog', $blog)
        ->with('ven_total', $ven_total)
        ->with('ven_mes', $ven_mes)
        ->with('ven_semana', $ven_semana)
        ->with('ventas_semana', $ventas_semana)
        ->with('ventas_mes', $ventas_mes)
        ->with('ventas_hoy', $ventas_hoy)
        ->with('venta_anual', $venta_anual)
        ->with('cierres_mensuales', $cierres_mensuales);
    }

    public function userProfile()
    {
        return view('back.users.profile');
    }

    public function updateProfile(Request $request, $id)
    {
        // Guardar datos a la BD, usar el modelo con funcion find() para encontrar el elemento que estamos editabdo por medio del ID
        $user = User::find($id);

        if($request->password == NULL){
            $user->name = $request->input('name');
            $user->email = $request->input('email');
        }else{
            $user->password = bcrypt($request->input('password'));
        }
        
        $user->save();

        // Mensaje de aviso server-side
        Session::flash('success', 'Tu cuenta se actualizó exitosamente.');
        return redirect()->route('admin.perfil');
    }

    public function updateImage(Request $request, $id)
    {
        $user = User::find($id);
        
        $user->image = $request->user_imagen;

        if ($request->hasFile('user_image')) {
            $user_image = $request->file('user_image');
            $filename = 'user_img' . time() . '.' . $user_image->getClientOriginalExtension();
            $location = public_path('img/usuarios/' . $filename);

            Image::make($user_image)->resize(400,null, function($constraint){ $constraint->aspectRatio(); })->save($location);

            $user->image = $filename;
        }

        $user->save();

        Session::flash('success', 'La imagen de tu perfil ha sido editada exitosamente.');
        return redirect()->route('admin.perfil');
    }
}

resources/views/back/blog/create.blade.php
@extends('back.layouts.app')

@section('stylesheets')

<link rel="stylesheet" href="{{ asset('back/assets/plugins/html5-editor/bootstrap-wysihtml5.css') }}" />
<link href="{{ asset('back/assets/plugins/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="{{ asset('back/assets/plugins/dropify/dist/css/dropify.min.css') }}">
@endsection

@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Nueva Publicación</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Inicio</a></li>
            <li class="breadcrumb-item">Blog</li>
            <li class="breadcrumb-item active">Agregar Nueva Publicación</li>
        </ol>
    </div>
</div>

<form method="POST" action="{{ route('blog.store') }}" enctype="multipart/form-data">
	{{ csrf_field() }}	

	<div class="row">
		<div class="col col-md-8">
			<div class="card">
				<div class="card-body">
					<h3>Publicación</h3>
					<hr>

					<div class="row">
						<div class="col col-md-12">
							<div class="form-group">
								<label for="title">Titulo</label>
								<input class="form-control" type="text" name="title" required="">
							</div>
						</div>

						<div class="col col-md-12">
							<div class="form-group">
								<label for="summary">Resumen</label>
								<textarea class="form-control" row="5" name="summary" required=""></textarea>
							</div>
						</div>

						<div class="col col-md-12">
							<div class="form-group">
								<label for="body">Cuerpo</label>
								<textarea id="mymce" name="body"></textarea>
							</div>
						</div>

						<div class="col col-md-6">
							<div class="form-group">
								<label for="category_id">Categoria</label>
								<select class="form-control select2" name="category_id" required="">
									@foreach($categorias as $cat)
										<option value="{{ $cat->id }}">{{ $cat->name }}</option>
									@endforeach
								</select>
							</div>
						</div>

						<div class="col col-md-6">
							<div class="form-group">
								<label for="autor_id">Autor</label>
								<select class="form-control select2" name="autor_id" required="">
									@foreach($autores as $aut)
										<option value="{{ $aut->id }}">{{ $aut->name }}</option>
									@endforeach
								</select>
							</div>
						</div>

						<div class="col col-md-12">
							<div class="form-group">
								<label for="tag_id[]">Etiquetas</label>
								<select class="form-control select2 select2-multiple" name="tag_id[]" multiple="multiple">
									@foreach($etiquetas as $tg)
										<option value="{{ $tg->id }}">{{ $tg->name }}</option>
									@endforeach
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>

			<hr>
			<div class="col-md-12">
		    	<div class="row justify-content-end">
		            <div class="col">
		                <div class="form-group text-right">
		                    <a href="{{ route('blog.index') }}" class="btn btn-link">Cancel</a>
		                    <button type="submit" class="btn btn-success btn-lg">Guardar</button>
		                </div>
		            </div>
		        </div>
		    </div>

		</div>

		<div class="col col-md-4">
			<div class="card">
				<div class="card-body">
					<h3>Opciones de Imágen</h3>
					<hr>

					<div class="form-group">
						<label for="image">Imagen de Portada</label>
						<input type="file" name="image" class="dropify" data-height="250" required="" />
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
@endsection

@section('scripts')
    <script src="{{ asset('back/assets/plugins/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>

    <script src="{{ asset('back/assets/plugins/tinymce/tinymce.min.js') }}"></script>

    <script src="{{ asset('back/assets/plugins/dropify/dist/js/dropify.min.js') }}"></script>
    <script>
    $(document).ready(function() {
        // Basic
        $('.dropify').dropify();
        $('.select2').select2();
    });
    </script>

    <script>
    $(document).ready(function() {

        if ($("#mymce").length > 0) {
            tinymce.init({
                selector: "textarea#mymce",
                theme: "modern",
                language: 'es_MX',
                height: 300,
                plugins: [
                    "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                    "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                    "save table contextmenu directionality emoticons template paste textcolor"
                ],
                toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons",

            });
        }
    });
    </script>
@endsection

resources/views/back/blog/index.blade.php
@extends('back.layouts.app')

@section('stylesheets')

@endsection

@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Blog</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Inicio</a></li>
            <li class="breadcrumb-item active">Publicaciones</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col">
        @include('back.layouts.partials._mensajes')
    </div>
</div>

<div class="row mb-4">
    <div class="col col-md-12">
        <a href="{{ route('blog.create') }}" class="btn btn-rounded btn-success"><i class="fa fa-plus-circle m-r-5"></i> Nueva Publicación</a>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h3>Publicaciones</h3>
                <hr>

                @if($publicaciones->count() == NULL || $publicaciones->count() == 0)
                    <p>No hay publicaciones. ¡Comienza a crear una!</p>
                @else 
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Titulo</th>
                                <th>Cuerpo</th>
                                <th>Categoría</th>
                                <th>Autor</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($publicaciones as $pub)
                            <tr>
                                <td>{{ $pub->id }}</td>
                                <td>{{ $pub->title }}</td>
                                <td>{{ $pub->summary }}</td>
                                <td><span class="label label-info">{{ $pub->categoria->name }}</span> </td>
                                <td>{{ $pub->autor->name }}</td>
                                <td class="text-nowrap">
                                    <a href="{{ route('blog.show', $pub->id) }}" data-toggle="tooltip" data-original-title="Ver"><i class="mdi mdi-eye text-inverse m-r-10"></i> </a>
                                    <a href="{{ route('blog.edit', $pub->id) }}" data-toggle="tooltip" data-original-title="Editar"><i class="mdi mdi-pencil text-inverse"></i></a>

                                    <form method="POST" class="delete" action="{{ route('blog.destroy', $pub->id) }}" style="display: inline-block;">
                                        <button type="submit" class="btn btn-sm btn-outline-danger" data-toggle="tooltip" data-original-title="Borrar"><i class="ti-trash"></i></button>
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                {{ $publicaciones->links() }}
                @endif
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card mb-3">
            <div class="card-body">
                <h3>Categorías</h3>
                <hr>

                <form method="POST" action="{{ route('categorias.store') }}">
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input class="form-control" name="name" placeholder="Nueva Categoria..." type="text">
                        <div class="input-group-addon" style="padding: 0px; background-color: transparent;"><button class="btn btn-success">Guardar</button></div>
                    </div>
                </form>

                @if($categorias->count() == NULL || $categorias->count() == 0)
                    <p class="mt-4 mb-0">No hay categorias. ¡Comienza a crear una!</p>
                @else
                    <ul class="list-group mt-4 mb-0">
                        @foreach($categorias as $cat)
                        <li class="list-group-item">{{ $cat->name }}</li>
                        @endforeach
                    </ul>               
                @endif
            </div>
        </div>

        <div class="card mb-3">
            <div class="card-body">
                <h3>Etiquetas</h3>
                <hr>

                <form method="POST" action="{{ route('etiquetas.store') }}">
                    {{ csrf_field() }}
                    <div class="input-group">
                        <input class="form-control" name="name" placeholder="Nueva Etiqueta..." type="text">
                        <div class="input-group-addon" style="padding: 0px; background-color: transparent;"><button class="btn btn-success">Guardar</button></div>
                    </div>
                </form>

                @if($etiquetas->count() == NULL || $etiquetas->count() == 0)
                    <p class="mt-4 mb-0">No hay etiquetas. ¡Comienza a crear una!</p>
                @else
                    <ul class="list-group mt-4 mb-0">
                        @foreach($etiquetas as $tg)
                        <li class="list-group-item">{{ $tg->name }}</li>
                        @endforeach
                    </ul>               
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(".delete").on("submit", function(){
        return confirm("¿Estás seguro de querer borrar la publicación? Si borras este elemento también se eliminarán las imágenes relacionados y no podrán ser recuperadas.");
    });
</script>
@endsection

resources/views/back/blog/show.blade.php
@extends('back.layouts.app')

@section('stylesheets')

@endsection

@section('content')
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Blog</h3>
    </div>
    <div class="col-md-7 align-self-center">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Inicio</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Publicaciones</a></li>
            <li class="breadcrumb-item active">{{ $publicacion->title }}</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col">
        @include('back.layouts.partials._mensajes')
    </div>
</div>

<div class="row mb-4">
    <div class="col col-md-12">
        <a href="{{ route('blog.index') }}" class="btn btn-rounded btn-success">Regresar</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3>{{ $publicacion->title }}</h3>
                <p>{{ $publicacion->summary }}</p>

                <img class="my-4" style="width: 100%;" src="{{ asset('img/blog/covers/' . $publicacion->image) }}">
                <ul class="list-inline">
                	<li class="list-inline-item">{{ $publicacion->autor->name }}</li>
                	<li class="list-inline-item">{{ $publicacion->categoria->name }}</li>
                </ul>

                {!! $publicacion->body !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')

@endsection